spring:
  application:
    name: carrent
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      generate_statistics: true
      session:
        events.log.LOG_QUERIES_SLOWER_THAN_MS: 1
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
#  cache:
#    type: redis
#  redis:
#    host: ${REDIS_CACHE_HOST:localhost}
#    port: ${REDIS_CACHE_PORT:6379}
#  session:
#    store-type: mongodb
#  kafka:
#    template:
#      email-topic: emails
#  data:
#    mongodb:
#      host: ${MONGODB_HOST:localhost}
#      port: ${MONGODB_PORT:27017}

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

server:
  port: ${APPLICATION_PORT:8080}

logging:
  level:
    org.hibernate.stat: DEBUG

jwt:
  secret: ${JWT_SECRET}
  header: Authorization
  accessTokenExpiration: 120
  refreshTokenExpiration: 86400

paypal:
  mode: sandbox
  clientId: ${PAYPAL_CLIENT_ID}
  clientSecret: ${PAYPAL_SECRET}

aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID}
      secret: ${AWS_ACCESS_KEY_SECRET}
  s3:
    region:
      name: ${AWS_S3_REGION}
    bucket:
      name: ${AWS_S3_BUCKET_NAME}

frontend:
  url: ${FRONTEND_LINK}